version: "3.7"

volumes:
    node_modules:
    obj:
    bin:

services:
    appdev:
        container_name: app-dev
        image: app:dev
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/usr/src/app
            - node_modules:/usr/src/app/ClientApp/node_modules/
            - obj:/usr/src/app/obj
            - bin:/usr/src/app/bin
        ports:
            - 80:80            
        command: tail -f /dev/null